<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Modernize Free</title>
  <link rel="shortcut icon" type="image/png" href="../../../../../resources/views/assets/images/logos/favicon.png" />
  <link rel="stylesheet" href="../../../../../resources/views/assets/css/styles.min.css" />
</head>

<body>
  <!--  Body Wrapper -->
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <!-- Sidebar Start -->
    <aside class="left-sidebar">
      <!-- Sidebar scroll-->
      <div>
        <div class="brand-logo d-flex align-items-center justify-content-between ms-3 mt-4">
          <a href="./task" class="btn btn-primary w-100 p-3">
            <i class="ti ti-plus"></i>
            &nbsp; <b>New task</b>
          </a>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
            <?php
              echo $response['sidebar'];
            ?>
        </nav>
      </div>
    </aside>
    <div class="body-wrapper">
      <div class="card m-5">
        <form class="w-100 p-4" method="post" action="./category">
            <div class="mb-4">
              <label for="exampleInputEmail1" class="form-label">Title</label>
              <input type="text" name="title" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" required>
            </div>
            
            <button type="submit" class="btn btn-primary">Create</button>
            <a type="button" class="btn btn-danger ms-2" href="./../home">Close</a>
        </form>
      </div>
      <?php
        echo $response['toast'];
      ?>
    </div>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
  <script src="../../../../../resources/views/assets/libs/jquery/dist/jquery.min.js"></script>
  <script src="../../../../../resources/views/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="../../../../../resources/views/assets/js/sidebarmenu.js"></script>
  <script src="../../../../../resources/views/assets/js/app.min.js"></script>
  <script src="../../../../../resources/views/assets/libs/apexcharts/dist/apexcharts.min.js"></script>
  <script src="../../../../../resources/views/assets/libs/simplebar/dist/simplebar.js"></script>
  <script src="../../../../../resources/views/assets/js/dashboard.js"></script>

</body>

</html>